-- VHDL Entity lab7_part2_lib.lab7_part2.symbol
--
-- Created:
--          by - xli146.ews (eceb-2022-05.ews.illinois.edu)
--          at - 17:25:29 03/03/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lab7_part2 IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END lab7_part2 ;

--
-- VHDL Architecture lab7_part2_lib.lab7_part2.struct
--
-- Created:
--          by - xli146.ews (eceb-2022-05.ews.illinois.edu)
--          at - 17:25:29 03/03/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF lab7_part2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_6' of 'inv'
   dout1 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_7' of 'inv'
   dout <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_8' of 'inv'
   dout2 <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_0' of 'nand'
   dout3 <= NOT(S2 AND dout);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'nand'
   dout4 <= NOT(dout1 AND dout2);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'nand'
   dout5 <= NOT(S2 AND S0);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   dout6 <= NOT(dout1 AND S1);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'nand'
   A <= NOT(dout3 AND dout4);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'nand'
   P <= NOT(dout5 AND dout6);

   -- Instance port mappings.

END struct;
