-- VHDL Entity lab5_lib.Full_Adder.symbol
--
-- Created:
--          by - xli146.ews (eceb-2022-04.ews.illinois.edu)
--          at - 14:27:57 02/17/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Full_Adder IS
   PORT( 
      Cin  : IN     std_logic;
      a    : IN     std_logic;
      b    : IN     std_logic;
      Cout : OUT    std_logic;
      S    : OUT    std_logic
   );

-- Declarations

END Full_Adder ;

--
-- VHDL Architecture lab5_lib.Full_Adder.struct
--
-- Created:
--          by - xli146.ews (eceb-2022-04.ews.illinois.edu)
--          at - 14:27:57 02/17/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lab5_lib;

ARCHITECTURE struct OF Full_Adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL f     : std_logic;


   -- Component Declarations
   COMPONENT my_xor
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      f : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : my_xor USE ENTITY lab5_lib.my_xor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_2' of 'and'
   dout <= a AND b;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout1 <= f AND Cin;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'or'
   Cout <= dout OR dout1;

   -- Instance port mappings.
   U_0 : my_xor
      PORT MAP (
         a => a,
         b => b,
         f => f
      );
   U_1 : my_xor
      PORT MAP (
         a => f,
         b => Cin,
         f => S
      );

END struct;
