-- VHDL Entity lab7_lib.lab9_state.symbol
--
-- Created:
--          by - xli146.ews (eceb-2022-38.ews.illinois.edu)
--          at - 20:49:12 03/19/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lab9_state IS
   PORT( 
      S0      : IN     std_logic;
      S1      : IN     std_logic;
      S2      : IN     std_logic;
      T       : IN     std_logic;
      S0_next : OUT    std_logic;
      S1_next : OUT    std_logic;
      S2_next : OUT    std_logic
   );

-- Declarations

END lab9_state ;

--
-- VHDL Architecture lab7_lib.lab9_state.struct
--
-- Created:
--          by - xli146.ews (eceb-2022-38.ews.illinois.edu)
--          at - 20:49:12 03/19/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF lab9_state IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_5' of 'and'
   S1_next <= S2 AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'and'
   S0_next <= dout2 AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'inv'
   dout <= NOT(T);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   S2_next <= NOT(dout);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout2 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout3 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout1 <= NOT(S0);

   -- Instance port mappings.

END struct;
